### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by khaldonno** [neojato/T-Hawk#5]
Really it's good job
but how can modify it to get only **latest tweets** and like it

thank u

**Comment by neojato** [comment]
Hi @khaldonno - 

By default the script returns the latest tweets. If you are seeing the script grab historical tweets, then you can use the `SINCE_TWITTER_ID` property from the array of tweets so that it will only show tweets newer than the selected id.

If you only want to like and not retweet, comment out [line 49](https://github.com/neojato/T-Hawk/blob/ac240d249f3e821d45a797e7ec4bf7c039b5c1b8/code.gs#L49).
